### ISSUE TITLE
Project Deprecation

### ISSUE THREAD

**Issue by braco** [netlify-templates/victor-hugo#530]
This repo is out of date. 

On a basic level, it's using an old webpack version that fails when compiling newer js modules. There are [important, ignored PRs](https://github.com/netlify-templates/victor-hugo/pulls
). From there, it's totally out of step with hugo development, and there are better ways to do almost everything from the [build pipeline](https://gohugo.io/hugo-pipes/js/) on out.

My company wasted about a week discovering this. When you have a canonical repo referenced in your documentation, being out of date with a technology compounds the pain of development for anybody that blithely wanders into the project. victor-hugo builds fine at the beginning, so the pain comes in when you start expanding the requirements of something you've already started, and problems are uncovered one by one, and you discover you've been building on outmoded patterns the entire time.

You could just build on top of Hyas, which is Netlify ready, properly maintained, and generally much better:
https://gethyas.com/

CC @erquhart, not sure who's controlling this repo

**Comment by timtorres** [comment]
I've had this exact experience with victor-hugo. I wish I would have known about Hyas...

**Comment by maxcell** [comment]
Howdy cool cats! I'm one of the new maintainers to the templates we support, so know that we've exchanged hands and this is a new era. I want to open with I appreciate the honest feedback and want to acknowledge how rough it must have been to bump against some of the rough edges due to maintenance. My focus is to investigate this repo and see how we can make sure everything is up to date. I saw some work was done already for dependencies on #531 and I will see what else needs to be done.

I also will take a gander over with Hyas!

Are there any particular feature sets you're hoping to see out of this repo that aren't currently there? Can you share any bumps you came across concretely?

**Comment by maxcell** [comment]
After a lot of conversation internally, we've decided that we are going to archive this repository and leave a note about using a tool like Hyas. I wanna take a second to thank you @braco for your honest feedback and pointing a direction for us to give support to. We care about making it easier for everyone to build on the web and we don't want to block that. I also wanna say thank you @timtorres for making a PR for addressing a place we'd need to.

The steps for us in this work for now is going to look like:
- Adding a deprecation notice in the README
- Archiving this repository so no more updates can be made
- Doing anything we'd need to make sure that the PR reaches the finish line

Thank you again you two, and all the folks who have helped the `victor-hugo` repo!
